-- Rode esse script no seu banco (o mesmo banco onde já estão USUARIOS, IDEIAS e COMENTARIOS)
CREATE TABLE REFRESH_TOKENS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USUARIOS_ID INT NOT NULL,
  TOKEN TEXT NOT NULL,
  EXPIRES_AT DATETIME,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_refresh_usuario
    FOREIGN KEY (USUARIOS_ID)
    REFERENCES USUARIOS(ID)
    ON DELETE CASCADE
);
